version: '3'
services:
    sim:
        image: vostro/genieacs-sim
        volumes:
            - 'var_log:/var/log'
        environment:
            - 'ACS_URL=http://genieacs.vostro.live:7547'
volumes:
    var_log:
        driver: local